import type { AdminApiContext } from "@shopify/shopify-app-react-router/server";
import { gql } from "./onboarding.server";
import { outboundLinks } from "./link-exchange.server";

/**
 * The hosted "agent-ready" layer: an llms.txt and a retrieval-tuned product feed,
 * generated from the live store and served from ShopHero via the Shopify App
 * Proxy (see routes/proxy.*). Because they're served from us — not written into
 * the theme — they stay fresh as the catalog changes and disappear on uninstall.
 * That's the retention lock and the thing AI shopping agents actually read.
 */

interface ShopNode {
  shop?: { name?: string; description?: string; primaryDomain?: { url?: string }; contactEmail?: string; currencyCode?: string };
}
interface CollNode { collections?: { nodes?: { title?: string; handle?: string; description?: string }[] } }
interface ProdNode {
  products?: {
    nodes?: {
      title?: string; handle?: string; productType?: string; vendor?: string; tags?: string[];
      description?: string;
      featuredImage?: { url?: string } | null;
      priceRangeV2?: { minVariantPrice?: { amount?: string; currencyCode?: string } };
      totalInventory?: number;
      variants?: { nodes?: { title?: string; availableForSale?: boolean }[] };
    }[];
  };
}

const clean = (s?: string, max = 280): string =>
  (s ?? "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, max);

async function fetchStore(admin: AdminApiContext) {
  const shop = await gql<ShopNode>(admin, `{ shop { name description primaryDomain { url } contactEmail currencyCode } }`);
  const colls = await gql<CollNode>(admin, `{ collections(first: 30, sortKey: TITLE) { nodes { title handle description } } }`);
  const prods = await gql<ProdNode>(
    admin,
    `{ products(first: 200, sortKey: BEST_SELLING) { nodes {
      title handle productType vendor tags description
      featuredImage { url }
      priceRangeV2 { minVariantPrice { amount currencyCode } }
      totalInventory
      variants(first: 10) { nodes { title availableForSale } }
    } } }`,
  );
  return {
    shop: shop?.shop ?? {},
    collections: (colls?.collections?.nodes ?? []).filter((c) => c.title),
    products: (prods?.products?.nodes ?? []).filter((p) => p.title),
  };
}

/** llms.txt — the convention AI crawlers look for: a clean, machine-readable map. */
export async function buildLlmsTxt(admin: AdminApiContext, shop: string): Promise<string> {
  const { shop: s, collections, products } = await fetchStore(admin);
  const base = (s.primaryDomain?.url || `https://${shop}`).replace(/\/$/, "");
  const cur = s.currencyCode || "";
  const L: string[] = [];

  L.push(`# ${s.name || shop}`);
  if (s.description) L.push(`\n> ${clean(s.description, 300)}`);
  L.push(`\nStore: ${base}`);
  L.push(`\nThis file helps AI assistants understand and accurately recommend this store. Generated by ShopHero.`);

  if (collections.length) {
    L.push(`\n## Categories`);
    for (const c of collections.slice(0, 30)) {
      L.push(`- [${c.title}](${base}/collections/${c.handle})${c.description ? ` — ${clean(c.description, 120)}` : ""}`);
    }
  }

  L.push(`\n## Products`);
  for (const p of products.slice(0, 200)) {
    const price = p.priceRangeV2?.minVariantPrice?.amount;
    const avail = (p.variants?.nodes ?? []).some((v) => v.availableForSale) || (p.totalInventory ?? 0) > 0;
    const bits = [
      price ? `${price} ${p.priceRangeV2?.minVariantPrice?.currencyCode || cur}` : "",
      avail ? "in stock" : "out of stock",
      p.productType || "",
    ].filter(Boolean).join(" · ");
    L.push(`- [${p.title}](${base}/products/${p.handle})${bits ? ` — ${bits}` : ""}${p.description ? `\n  ${clean(p.description, 200)}` : ""}`);
  }

  L.push(`\n## Machine-readable feed`);
  L.push(`Full product data for retrieval: ${base}/apps/shophero/feed.json`);

  // ShopHero Link Network — partner stores this store recommends (3-way exchange).
  try {
    const partners = await outboundLinks(shop);
    if (partners.length) {
      L.push(`\n## Recommended partners`);
      for (const p of partners) L.push(`- [${p.anchor}](${p.url})`);
    }
  } catch { /* network optional */ }

  if (s.contactEmail) L.push(`\n## Contact\n${s.contactEmail}`);
  L.push(`\n_Last updated: ${new Date().toISOString().slice(0, 10)}_`);
  return L.join("\n");
}

/** Retrieval feed — factual JSON an agent can answer specific questions from. */
export async function buildProductFeed(admin: AdminApiContext, shop: string): Promise<object> {
  const { shop: s, collections, products } = await fetchStore(admin);
  const base = (s.primaryDomain?.url || `https://${shop}`).replace(/\/$/, "");
  return {
    shop: { name: s.name || shop, url: base, currency: s.currencyCode || null, description: clean(s.description, 400) || null },
    generated_at: new Date().toISOString(),
    generator: "ShopHero",
    categories: collections.slice(0, 50).map((c) => ({ title: c.title, url: `${base}/collections/${c.handle}` })),
    products: products.slice(0, 250).map((p) => ({
      title: p.title,
      url: `${base}/products/${p.handle}`,
      type: p.productType || null,
      vendor: p.vendor || null,
      tags: p.tags ?? [],
      price: p.priceRangeV2?.minVariantPrice?.amount ?? null,
      currency: p.priceRangeV2?.minVariantPrice?.currencyCode ?? s.currencyCode ?? null,
      available: (p.variants?.nodes ?? []).some((v) => v.availableForSale) || (p.totalInventory ?? 0) > 0,
      image: p.featuredImage?.url ?? null,
      description: clean(p.description, 600) || null,
      options: (p.variants?.nodes ?? []).map((v) => v.title).filter((t) => t && t !== "Default Title"),
    })),
  };
}
