/**
 * Guided feature flows — what opens when a merchant taps a feature tile.
 * Each flow is: an INTRO (what it does + what's ahead) → 2–5 qualifying questions
 * (some branching / store-aware) → a tailored, ranked checklist generated by the
 * decompose engine from the answers. Data-driven so flows are easy to tune/add.
 */
export interface FlowOption { label: string; value: string; hint?: string }
export interface FlowStep {
  id: string;
  q: string;
  help?: string;
  options: FlowOption[];
  multi?: boolean;        // allow multiple selections
  allowText?: boolean;    // also accept a typed answer
  showIf?: (a: Answers) => boolean; // branching: only show when true
}
export type Answers = Record<string, string[]>;
export interface FeatureFlow {
  key: string;
  emoji: string;
  title: string;
  blurb: string;          // one-line promise
  ahead: string[];        // "here's what's ahead" bullets
  steps: FlowStep[];
  goal: (a: Answers) => string; // builds the decompose goal from answers
}

const list = (a: Answers, id: string, fallback = "any") => (a[id]?.length ? a[id].join(", ") : fallback);
const one = (a: Answers, id: string, fallback = "") => a[id]?.[0] ?? fallback;

// Common closing questions reused across flows.
const Q_PUBLISH: FlowStep = {
  id: "publish", q: "How should changes go out?",
  options: [
    { label: "Stage for my approval", value: "stage", hint: "Recommended — preview, then Accept" },
    { label: "Save as drafts where possible", value: "draft" },
  ],
};
const Q_VOICE: FlowStep = {
  id: "voice", q: "Whose words?",
  options: [
    { label: "Write it for me (on-brand)", value: "ai" },
    { label: "I'll provide my own copy", value: "own" },
  ],
};
const Q_OWN_TEXT: FlowStep = {
  id: "ownText", q: "Paste what you'd like to use", help: "Headline, key points, or full copy — I'll polish and place it.",
  options: [], allowText: true,
  showIf: (a) => one(a, "voice") === "own",
};

export const FEATURE_FLOWS: Record<string, FeatureFlow> = {
  sales: {
    key: "sales", emoji: "📈", title: "Increase Conversions",
    blurb: "Find what's quietly stopping visitors from buying — and fix it.",
    ahead: ["A read of your store for conversion blockers", "A few quick questions to focus the work", "A ranked checklist you run one tap at a time"],
    steps: [
      { id: "goal", q: "What matters most right now?", multi: true, options: [
        { label: "More add-to-carts", value: "more add-to-carts" },
        { label: "Fewer abandoned carts", value: "fewer abandoned carts" },
        { label: "Higher order value", value: "higher AOV (upsells/bundles)" },
        { label: "More trust & credibility", value: "more trust" },
      ] },
      { id: "where", q: "Where should we focus first?", options: [
        { label: "Product pages", value: "product pages" },
        { label: "Homepage", value: "homepage" },
        { label: "Cart & checkout path", value: "cart and checkout" },
        { label: "Whole store", value: "the whole store" },
      ] },
      { id: "depth", q: "How deep should we go?", options: [
        { label: "Quick wins only", value: "quick high-impact wins" },
        { label: "A thorough pass", value: "a thorough, comprehensive pass" },
      ] },
      Q_PUBLISH,
    ],
    goal: (a) => `Increase conversions, focused on ${list(a, "where", "the store")}. Priorities: ${list(a, "goal", "more sales")}. Scope: ${one(a, "depth", "high-impact wins")}. First analyze the store for conversion blockers — weak/again unclear CTAs, missing trust signals, no urgency or social proof, thin product pages, no reviews, slow load, cart friction — then build a ranked checklist of concrete fixes (sections, copy, trust, offers). Changes ${one(a, "publish") === "draft" ? "saved as drafts where possible" : "staged for approval"}.`,
  },

  improve: {
    key: "improve", emoji: "✨", title: "Improve My Store",
    blurb: "A ranked plan of the highest-impact fixes for your store.",
    ahead: ["A full scan across SEO, conversion, content & trust", "A couple of questions to set priorities", "A ranked, tap-to-run plan"],
    steps: [
      { id: "goal", q: "What's your top goal?", multi: true, options: [
        { label: "More sales", value: "more sales" },
        { label: "More traffic", value: "more traffic" },
        { label: "Look more professional", value: "a more professional look" },
        { label: "Get AI/Google-ready", value: "AI and Google visibility" },
      ] },
      { id: "effort", q: "How much do you want to take on?", options: [
        { label: "Just the top 3–5 wins", value: "the top 3-5 wins" },
        { label: "A full roadmap", value: "a full roadmap" },
      ] },
      Q_PUBLISH,
    ],
    goal: (a) => `Improve my store for ${list(a, "goal", "more sales")}. Give me ${one(a, "effort", "the top wins")} as a ranked checklist, drawn from a scan of my store. Changes ${one(a, "publish") === "draft" ? "as drafts" : "staged for approval"}.`,
  },

  redesign: {
    key: "redesign", emoji: "🎨", title: "Redesign a Page",
    blurb: "Make any page feel premium and on-brand — fast.",
    ahead: ["Pick the page and the vibe", "I match your colors, fonts & brand", "A staged redesign you preview before it's live"],
    steps: [
      { id: "page", q: "Which page?", options: [
        { label: "Homepage", value: "homepage" }, { label: "A product page", value: "a product page" },
        { label: "Collection page", value: "a collection page" }, { label: "About / story", value: "the about page" },
      ], allowText: true },
      { id: "vibe", q: "What feel are you going for?", options: [
        { label: "Premium & minimal", value: "premium and minimal" }, { label: "Bold & modern", value: "bold and modern" },
        { label: "Warm & friendly", value: "warm and friendly" }, { label: "Match my current brand", value: "consistent with my current brand" },
      ] },
      { id: "focus", q: "What should the page push hardest?", multi: true, options: [
        { label: "A clear value proposition", value: "a clear value proposition" }, { label: "A strong CTA", value: "a strong CTA" },
        { label: "Trust & social proof", value: "trust and social proof" }, { label: "Featured products", value: "featured products" },
      ] },
      Q_PUBLISH,
    ],
    goal: (a) => `Redesign ${one(a, "page", "the homepage")} to feel ${one(a, "vibe", "premium")}, matching my colors, fonts and Brand Kit. Emphasize ${list(a, "focus", "the value prop and CTA")}. Staged for approval.`,
  },

  descriptions: {
    key: "descriptions", emoji: "✍️", title: "Make Products Irresistible",
    blurb: "Benefit-led, on-brand product copy that sells.",
    ahead: ["Choose which products & the angle", "I write skimmable, SEO-friendly copy", "Review before/after, then apply"],
    steps: [
      { id: "scope", q: "Which products?", options: [
        { label: "Ones with thin/missing copy", value: "products with thin or missing descriptions" },
        { label: "A specific product", value: "a specific product" },
        { label: "All products", value: "all products" },
      ] },
      { id: "angle", q: "What should the copy lead with?", multi: true, options: [
        { label: "Benefits & outcomes", value: "benefits and outcomes" }, { label: "Quality & materials", value: "quality and materials" },
        { label: "Who it's for / use-cases", value: "who it's for and use-cases" }, { label: "What's included", value: "what's included" },
      ] },
      Q_VOICE, Q_OWN_TEXT, Q_PUBLISH,
    ],
    goal: (a) => `Rewrite product descriptions for ${one(a, "scope", "products that need it")}, benefit-led and on-brand, leading with ${list(a, "angle", "benefits")}. ${one(a, "voice") === "own" ? `Use my notes: ${one(a, "ownText")}.` : "Use my Brand Kit voice."} Show before/after; ${one(a, "publish") === "draft" ? "save drafts" : "apply on approval"}.`,
  },

  blog: {
    key: "blog", emoji: "📝", title: "Publish a Blog Post",
    blurb: "SEO/AEO content that brings buyers in.",
    ahead: ["Pick a topic (or I suggest the best ones)", "I write a complete, on-brand article", "Review, then publish or save a draft"],
    steps: [
      { id: "topic", q: "What should it be about?", options: [
        { label: "Suggest the best topics for me", value: "the highest-value topic for this store" },
        { label: "A buying guide", value: "a buying guide" }, { label: "How-to / tips", value: "a how-to guide" },
        { label: "Product comparison", value: "a product comparison" },
      ], allowText: true },
      { id: "intent", q: "Who's it for?", options: [
        { label: "Ready-to-buy shoppers", value: "buyers with high purchase intent" },
        { label: "People just researching", value: "early-stage researchers" },
      ] },
      { id: "publish", q: "Publish or draft?", options: [
        { label: "Publish it live", value: "publish" }, { label: "Save as a draft to review", value: "draft" },
      ] },
    ],
    goal: (a) => `Write ${one(a, "topic", "the best article for this store")}, aimed at ${one(a, "intent", "buyers")}, SEO/AEO-optimized and on-brand with internal links. ${one(a, "publish") === "draft" ? "Save it as a draft." : "Publish it live."}`,
  },

  google: {
    key: "google", emoji: "🔍", title: "Rank Higher on Google",
    blurb: "Fix the SEO that's costing you traffic.",
    ahead: ["Pick what to optimize", "I fix titles, meta, structure & schema", "Staged for your approval"],
    steps: [
      { id: "scope", q: "What should we optimize?", multi: true, options: [
        { label: "Product pages", value: "product page SEO" }, { label: "Collections", value: "collection SEO" },
        { label: "Homepage", value: "homepage SEO" }, { label: "Structured data (schema)", value: "structured data" },
      ] },
      { id: "keywords", q: "Any target keywords or focus?", help: "Optional — type terms you want to rank for, or skip.", options: [
        { label: "Let ShopHero decide", value: "auto" },
      ], allowText: true },
      Q_PUBLISH,
    ],
    goal: (a) => `Improve SEO for ${list(a, "scope", "the store")} — titles, meta descriptions, headings, internal links and structured data.${one(a, "keywords") && one(a, "keywords") !== "auto" ? ` Target: ${one(a, "keywords")}.` : ""} Show before/after; staged for approval.`,
  },

  trust: {
    key: "trust", emoji: "🛡️", title: "Build Customer Trust",
    blurb: "Add the signals that make first-time buyers feel safe.",
    ahead: ["Pick the trust signals to add", "I place them on-brand", "Staged for your approval"],
    steps: [
      { id: "signals", q: "Which trust signals?", multi: true, options: [
        { label: "Guarantees / returns", value: "a guarantee & returns callout" }, { label: "Secure-checkout & payment badges", value: "secure-checkout and payment badges" },
        { label: "Reviews / testimonials", value: "reviews and testimonials" }, { label: "Shipping & support info", value: "shipping and support info" },
      ] },
      { id: "where", q: "Where should they go?", options: [
        { label: "Product pages", value: "product pages" }, { label: "Homepage", value: "homepage" }, { label: "Both", value: "homepage and product pages" },
      ] },
      Q_PUBLISH,
    ],
    goal: (a) => `Add trust signals (${list(a, "signals", "guarantee, badges, reviews")}) to ${one(a, "where", "the store")}, on-brand and only with TRUE claims (never invent reviews). Staged for approval.`,
  },

  faq: {
    key: "faq", emoji: "❓", title: "Answer Customer Questions",
    blurb: "An FAQ that removes objections and helps you get found.",
    ahead: ["Pick the questions to cover", "I write clear answers (+ FAQ schema)", "Staged for your approval"],
    steps: [
      { id: "topics", q: "What should the FAQ cover?", multi: true, options: [
        { label: "Shipping & delivery", value: "shipping and delivery" }, { label: "Returns & guarantee", value: "returns and guarantee" },
        { label: "Sizing / fit / specs", value: "sizing and specs" }, { label: "Product & usage questions", value: "product and usage questions" },
      ] },
      { id: "where", q: "Where should it live?", options: [
        { label: "Product pages", value: "product pages" }, { label: "A dedicated FAQ page", value: "a dedicated FAQ page" }, { label: "Homepage", value: "homepage" },
      ] },
      Q_VOICE, Q_OWN_TEXT,
    ],
    goal: (a) => `Add an FAQ covering ${list(a, "topics", "shipping, returns, sizing")} on ${one(a, "where", "product pages")}, that also emits FAQ schema. ${one(a, "voice") === "own" ? `Use my answers: ${one(a, "ownText")}.` : "Write clear, on-brand answers."}`,
  },

  speed: {
    key: "speed", emoji: "⚡", title: "Speed Up My Store",
    blurb: "Faster pages convert better — let's trim the weight.",
    ahead: ["Confirm what to optimize", "I apply safe speed fixes", "Staged, with the expected impact"],
    steps: [
      { id: "fixes", q: "What can we optimize?", multi: true, options: [
        { label: "Image loading", value: "lazy-load below-the-fold images" }, { label: "Unused CSS / sections", value: "remove unused CSS and sections" },
        { label: "Script & font loading", value: "defer non-critical scripts and preload fonts" }, { label: "Everything safe", value: "all safe speed fixes" },
      ] },
      Q_PUBLISH,
    ],
    goal: (a) => `Improve storefront speed: ${list(a, "fixes", "safe speed fixes")} (keep the hero/LCP image eager). Summarize the expected Core Web Vitals impact and any merchant actions. Staged for approval.`,
  },
};
