import type { LoaderFunctionArgs } from "react-router";
import { authenticate } from "../shopify.server";
import { buildLlmsTxt } from "../lib/agent-feed.server";
import { logCrawlerHit } from "../lib/crawler-log.server";

/**
 * Served at {shop}/apps/shophero/llms.txt via Shopify App Proxy. Hosted by us —
 * not written into the theme — so it stays fresh and vanishes on uninstall.
 * Shopify signs the proxied request; authenticate.public.appProxy verifies it.
 */
export async function loader({ request }: LoaderFunctionArgs) {
  const { session, admin } = await authenticate.public.appProxy(request);
  if (!session?.shop || !admin) {
    return new Response("Not found", { status: 404, headers: { "Content-Type": "text/plain" } });
  }
  logCrawlerHit(request, session.shop, "llms.txt");
  let body: string;
  try {
    body = await buildLlmsTxt(admin, session.shop);
  } catch {
    body = `# ${session.shop}\n\nStore catalog is being prepared. Generated by ShopHero.`;
  }
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
